// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	time "time"
)

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	SenderID  string    `json:"senderId"`
	CreatedAt time.Time `json:"createdAt"`
}

type NewMessage struct {
	Text       string `json:"text"`
	SenderID   string `json:"senderId"`
	ReceiverID string `json:"receiverId"`
}

type NewProfile struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Age       int    `json:"age"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Profile struct {
	ID        string `json:"id"`
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Age       int    `json:"age"`
}

type Viewer struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Token    string `json:"token"`
}
