// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	time "time"
)

type Chatroom struct {
	ID       string    `json:"id"`
	Messages []Message `json:"messages"`
}

type LoginInput struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	CreatedBy string    `json:"createdBy"`
	CreatedAt time.Time `json:"createdAt"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Viewer struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Token    string `json:"token"`
}
